import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import NavMenu from "./NavMenu";
import AuthProvider from "./AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={`${inter.className} bg-gray-200`}>
          <div className="max-w-3xl mt-10 mx-auto lg:max-w-7xl pt-2 px-4 pb-8">
            <NavMenu />
            <div className="bg-white p-4">{children}</div>
          </div>
          <footer className="pt-8 pb-16 px-20 mx-auto text-center">
            <p>Created by the ruoja</p>

            <div className="flex items-center justify-center gap-2">
              <Link href="/about">About</Link>
              <a href="www.youtube.com">Youtube</a>
              <a href="www.github.com">Source</a>
              <a href="www.nextjs.com">NextJs Docs</a>
            </div>
          </footer>
        </body>
      </html>
    </AuthProvider>
  );
}
