import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="max-w-3xl mx-auto lg:max-w-7xl">
          <nav className="flex justify-between items-center px-4 py-6 border-b border-gray-600">
            <h1>
              <span className="italic text-xl text-black">Lo</span>
              <span className="font-bold text-xl text-blue-600">go</span>
            </h1>
            <ul className="flex items-center gap-6  ">
              <li className="text-2xl font-bold text-blue-600 hover:text-blue-800">
                <Link href="/">Home</Link>
              </li>

              <li className="text-2xl font-bold text-blue-600 hover:text-blue-800">
                <Link href="/notes">Notes</Link>
              </li>
            </ul>
          </nav>
          {children}
        </main>
      </body>
    </html>
  );
}
